export const pricingList = [
  {
    name: "Prototype",
    price: "3500",
    timePeriod: "2-3",
    desc: "asfskdjhfkjasdfjasdbfiuasdbfasjkdbfaskdfbuasidbasdasfksdjfaoidjfuaoipsjdfoipajsdofpiajsdfoiasjdfoiajsdoifjaoidsfausdhiuasdhfuiashdfiuvs",
    services: [
      "Naming/Domain",
      "Logo",
      "Color Palette & Typography",
      "LandingPage",
      "CopyWriting",
      "Software Mockups",
    ],
  },
  {
    name: "Mvp",
    price: "7500",
    timePeriod: "5-6",
    desc: "asfskdjhfkjasdfjasdbfiuasdbfasjkdbfaskdfbuasidbvs",
    services: [
      "Naming/Domain",
      "Everything in Prototype",
      "Website (2-3 pages)",
      "Color Palette & Typography",
      "User Authentication",
      "CopyWriting",
      "Payments Integration",
      "Api Integration",
    ],
  },
  {
    name: "Custom",
    price: "12000",
    timePeriod: "7-8",
    desc: "asfskdjhfkjasdfjasdbfiuasdbfasjkdbfaskdfbuasidbvs",
    services: [
      "Naming/Domain",
      "Logo",
      "Color Palette & Typography",
      "LandingPage",
      "CopyWriting",
      "Software Mockups",
    ],
  },
];
